### ISSUE TITLE
D3 - (frontend) handle submit survey from user

### ISSUE THREAD

**Issue by tejash-patel** [rafiddewan/4806-Project#29]
- The user fills out a survey we need to make PATCH requests to the api endpoints which should contain the user's answers.
- Validate the data if its the user correctly enters it
  - make sure they arent empty (openended + numerical)
  - within a range (numerical)
  - an option is chosen (MCQ)

**Comment by rafiddewan** [comment]
Here is the handlePostRequest function you can use to submit the survey function https://github.com/rafiddewan/4806-Project/blob/db4159febe402454741162cb4af0626e8a9e2177/src/main/resources/static/surveyor.js#L190

You can also handle answers like I did here: https://github.com/rafiddewan/4806-Project/blob/main/src/main/resources/static/surveyor.js#L215
We might need to talk on how we would go about submitting answers however
